export const NEW_DATA = "NEW_DATA";
export const CLEAR_GRID = "CLEAR_GRID";
export const UPDATE_SPINNER = "UPDATE_SPINNER";
export const RESET_SAMPLE_PUZZLE = "RESET_SAMPLE_PUZZLE";
export const RETRIEVE_SOLUTION_STARTING = "RETRIEVE_SOLUTION_STARTING";
export const RETRIEVE_SOLUTION_SUCCESS = "RETRIEVE_SOLUTION_SUCCESS";
export const RETRIEVE_PUZZLE_STARTING = "RETRIEVE_PUZZLE_STARTING";
export const RETRIEVE_PUZZLE_SUCCESS = "RETRIEVE_PUZZLE_SUCCESS";

//control actions
export const TOGGLE_PENCIL = 'TOGGLE_PENCIL';
export const PENCIL_SELECTION_CHANGED = 'PENCIL_SELECTION_CHANGED';
export const PENCIL_UPDATE_FOR_SQUARE = 'PENCIL_UPDATE_FOR_SQUARE';
export const VALUE_UPDATE_FOR_SQUARE = 'VALUE_UPDATE_FOR_SQUARE';