name: React build and deploy to GitHub Pages
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: kevinhooke/sudoku-react-app
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - name: Deploy
        env:
          MY_EMAIL: kevin.hooke@gmail.com
          MY_NAME: kevinhooke
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://${{ MY_NAME }}:${{ secrets.GH_SECRET }}@github.com/kevinhooke/sudoku-react-app.git
          npm run deploy
